spin_manifest_version = 2

[application]
name = "demo-website"
version = "0.1.0"
authors = ["vamshireddy <vamshiproject02@gmail.com>"]
description = "timepass"

[[trigger.http]]
route = "/..."
component = "demo-website"

[component.demo-website]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "meshery.io/_site", destination = "/" }]

[component.demo-website.build]
watch = ["src/**"]
command = "make site"
workdir = "meshery.io"
